# Generated by Django 6.0.1 on 2026-02-21 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_normalize_college_major_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('student_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='学号')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_students', to='accounts.college', verbose_name='学院')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_students', to='accounts.grade', verbose_name='年级')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_students', to='accounts.major', verbose_name='专业')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolGateAccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='时间')),
                ('gate_location', models.CharField(db_index=True, max_length=50, verbose_name='校门位置')),
                ('direction', models.CharField(choices=[('in', '进'), ('out', '出')], db_index=True, max_length=3, verbose_name='进出方向')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_records', to='staff_dashboard.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '校门门禁记录',
                'verbose_name_plural': '校门门禁记录',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetworkAccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(db_index=True, verbose_name='结束时间')),
                ('use_vpn', models.BooleanField(db_index=True, verbose_name='是否使用VPN')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_records', to='staff_dashboard.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '网络访问记录',
                'verbose_name_plural': '网络访问记录',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DormitoryAccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='时间')),
                ('building', models.CharField(db_index=True, max_length=50, verbose_name='寝室楼栋')),
                ('direction', models.CharField(choices=[('in', '进'), ('out', '出')], db_index=True, max_length=3, verbose_name='进出方向')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorm_records', to='staff_dashboard.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '寝室门禁记录',
                'verbose_name_plural': '寝室门禁记录',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CanteenConsumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, help_text='格式：2025-02', max_length=7, verbose_name='月份')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='消费金额')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_records', to='staff_dashboard.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '食堂消费记录',
                'verbose_name_plural': '食堂消费记录',
                'ordering': ['-month', 'student__student_id'],
            },
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, help_text='格式：2025-02', max_length=7, verbose_name='月份')),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='平均成绩')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='staff_dashboard.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '成绩记录',
                'verbose_name_plural': '成绩记录',
                'ordering': ['-month', 'student__student_id'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['college', 'major', 'grade'], name='staff_dashb_college_555567_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['college', 'grade'], name='staff_dashb_college_4fb077_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['major', 'grade'], name='staff_dashb_major_i_9bd43e_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolgateaccessrecord',
            index=models.Index(fields=['student', 'timestamp'], name='staff_dashb_student_63a72a_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolgateaccessrecord',
            index=models.Index(fields=['student', '-timestamp'], name='staff_dashb_student_681d11_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolgateaccessrecord',
            index=models.Index(fields=['timestamp', 'direction'], name='staff_dashb_timesta_6ecd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolgateaccessrecord',
            index=models.Index(fields=['gate_location', 'timestamp'], name='staff_dashb_gate_lo_9462f8_idx'),
        ),
        migrations.AddIndex(
            model_name='networkaccessrecord',
            index=models.Index(fields=['student', 'start_time'], name='staff_dashb_student_bf320d_idx'),
        ),
        migrations.AddIndex(
            model_name='networkaccessrecord',
            index=models.Index(fields=['student', '-start_time'], name='staff_dashb_student_882262_idx'),
        ),
        migrations.AddIndex(
            model_name='networkaccessrecord',
            index=models.Index(fields=['start_time', 'end_time'], name='staff_dashb_start_t_287ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='networkaccessrecord',
            index=models.Index(fields=['use_vpn', 'start_time'], name='staff_dashb_use_vpn_d9738a_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitoryaccessrecord',
            index=models.Index(fields=['student', 'timestamp'], name='staff_dashb_student_28511b_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitoryaccessrecord',
            index=models.Index(fields=['student', '-timestamp'], name='staff_dashb_student_febe09_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitoryaccessrecord',
            index=models.Index(fields=['timestamp', 'direction'], name='staff_dashb_timesta_a7bc99_idx'),
        ),
        migrations.AddIndex(
            model_name='dormitoryaccessrecord',
            index=models.Index(fields=['building', 'timestamp'], name='staff_dashb_buildin_2e9880_idx'),
        ),
        migrations.AddIndex(
            model_name='canteenconsumptionrecord',
            index=models.Index(fields=['student', 'month'], name='staff_dashb_student_d0ae64_idx'),
        ),
        migrations.AddIndex(
            model_name='canteenconsumptionrecord',
            index=models.Index(fields=['month', 'amount'], name='staff_dashb_month_e832f2_idx'),
        ),
        migrations.AddIndex(
            model_name='canteenconsumptionrecord',
            index=models.Index(fields=['-amount'], name='staff_dashb_amount_c2cd4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='canteenconsumptionrecord',
            unique_together={('student', 'month')},
        ),
        migrations.AddIndex(
            model_name='academicrecord',
            index=models.Index(fields=['student', 'month'], name='staff_dashb_student_0a1faf_idx'),
        ),
        migrations.AddIndex(
            model_name='academicrecord',
            index=models.Index(fields=['month', 'average_score'], name='staff_dashb_month_8284a3_idx'),
        ),
        migrations.AddIndex(
            model_name='academicrecord',
            index=models.Index(fields=['-average_score'], name='staff_dashb_average_3ab78a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academicrecord',
            unique_together={('student', 'month')},
        ),
    ]
