# Generated by Django 6.0.1 on 2026-02-23 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('canteen', '食堂消费记录'), ('school_gate', '校门门禁记录'), ('dormitory', '寝室门禁记录'), ('network', '网络访问记录'), ('academic', '成绩记录')], db_index=True, max_length=20, verbose_name='数据类型')),
                ('start_date', models.DateField(db_index=True, verbose_name='统计开始日期')),
                ('end_date', models.DateField(db_index=True, verbose_name='统计结束日期')),
                ('statistics_data', models.JSONField(default=dict, verbose_name='统计数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='staff_dashboard.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '数据统计',
                'verbose_name_plural': '数据统计',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['student', 'data_type', 'start_date', 'end_date'], name='staff_dashb_student_ac15e7_idx'), models.Index(fields=['data_type', 'updated_at'], name='staff_dashb_data_ty_3fff60_idx')],
                'unique_together': {('student', 'data_type', 'start_date', 'end_date')},
            },
        ),
    ]
