# Generated by Django 6.0.1 on 2026-02-28 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_dashboard', '0002_datastatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('canteen', '食堂消费记录'), ('school_gate', '校门门禁记录'), ('dormitory', '寝室门禁记录'), ('network', '网络访问记录'), ('academic', '成绩记录')], db_index=True, max_length=20, verbose_name='数据类型')),
                ('date', models.DateField(db_index=True, verbose_name='统计日期')),
                ('statistics_data', models.JSONField(default=dict, verbose_name='统计数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='datastatistics',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='datastatistics',
            name='staff_dashb_student_ac15e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='datastatistics',
            name='staff_dashb_data_ty_3fff60_idx',
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_statistics', to='staff_dashboard.student', verbose_name='学生'),
        ),
        migrations.RemoveField(
            model_name='datastatistics',
            name='student',
        ),
        migrations.AddIndex(
            model_name='dailystatistics',
            index=models.Index(fields=['student', 'data_type', 'date'], name='staff_dashb_student_ba999e_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystatistics',
            index=models.Index(fields=['data_type', 'date'], name='staff_dashb_data_ty_f483d5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystatistics',
            index=models.Index(fields=['date'], name='staff_dashb_date_c93b44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailystatistics',
            unique_together={('student', 'data_type', 'date')},
        ),
        migrations.DeleteModel(
            name='DataStatistics',
        ),
    ]
