# Generated by Django 6.0.1 on 2026-02-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_name_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('counselor', '辅导员'), ('admin', '系统管理员')], default='student', max_length=20, verbose_name='角色'),
        ),
    ]
