# Generated by Django 6.0.1 on 2026-02-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_position_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_role_approved',
            field=models.BooleanField(default=False, help_text='辅导员和管理员角色需要管理员审核后才能登录', verbose_name='角色是否审核通过'),
        ),
    ]
