# Generated by Django 6.0.1 on 2026-02-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_role_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_role_approved',
        ),
        migrations.AddField(
            model_name='user',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('student', '学生'), ('counselor', '辅导员'), ('admin', '系统管理员')], help_text='用户请求变更的目标身份，空表示无待审核请求', max_length=20, null=True, verbose_name='请求身份'),
        ),
    ]
