# Generated by Django 6.0.1 on 2026-02-19 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_is_role_approved_user_requested_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='学院名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='学院代码')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='入学年份')),
                ('name', models.CharField(max_length=20, verbose_name='年级名称')),
            ],
            options={
                'verbose_name': '年级',
                'verbose_name_plural': '年级',
                'ordering': ['-year'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='managed_colleges',
            field=models.ManyToManyField(blank=True, related_name='managers', to='accounts.college', verbose_name='负责学院（辅导员/管理员）'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.college', verbose_name='所属学院（学生）'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_grades',
            field=models.ManyToManyField(blank=True, related_name='managers', to='accounts.grade', verbose_name='负责年级（辅导员/管理员）'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.grade', verbose_name='所属年级（学生）'),
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='专业名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='专业代码')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='accounts.college', verbose_name='所属学院')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
                'ordering': ['code'],
                'unique_together': {('college', 'name')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='managed_majors',
            field=models.ManyToManyField(blank=True, related_name='managers', to='accounts.major', verbose_name='负责专业（辅导员/管理员）'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.major', verbose_name='所属专业（学生）'),
        ),
        migrations.CreateModel(
            name='ProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('student_info', '学生信息变更'), ('manager_info', '辅导员/管理员信息变更')], max_length=20, verbose_name='变更类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('requested_managed_colleges', models.TextField(blank=True, default='', verbose_name='申请负责的学院ID列表（JSON）')),
                ('requested_managed_majors', models.TextField(blank=True, default='', verbose_name='申请负责的专业ID列表（JSON）')),
                ('requested_managed_grades', models.TextField(blank=True, default='', verbose_name='申请负责的年级ID列表（JSON）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='审核意见')),
                ('requested_student_college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_change_requests', to='accounts.college', verbose_name='申请变更的学院（学生）')),
                ('requested_student_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_change_requests', to='accounts.grade', verbose_name='申请变更的年级（学生）')),
                ('requested_student_major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_change_requests', to='accounts.major', verbose_name='申请变更的专业（学生）')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '信息变更申请',
                'verbose_name_plural': '信息变更申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
