# Generated by Django 6.0.1 on 2026-02-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_normalize_college_major_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='requested_role',
        ),
        migrations.AddField(
            model_name='profilechangerequest',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('student', '学生'), ('counselor', '辅导员'), ('admin', '系统管理员')], max_length=20, null=True, verbose_name='申请变更的角色'),
        ),
        migrations.AlterField(
            model_name='profilechangerequest',
            name='change_type',
            field=models.CharField(choices=[('role_change', '角色变更'), ('student_info', '学生信息变更'), ('manager_info', '辅导员/管理员信息变更')], max_length=20, verbose_name='变更类型'),
        ),
    ]
