# Generated by Django 6.0.1 on 2026-02-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_normalize_college_major_codes'),
        ('accounts', '0008_remove_user_requested_role_and_more'),
    ]

    operations = [
    ]
