"""
Django settings for school_platform project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-53j_bl9ycppk9-c%@n_e5_q&e*l2u#=%m%he5jq1bg=%a^vh8l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 允许的主机名（必须配置）
ALLOWED_HOSTS = ['rtfox.top', 'www.rtfox.top', '127.0.0.1', 'localhost']

# CSRF 信任的来源（关键配置）
CSRF_TRUSTED_ORIGINS = [
    'https://rtfox.top',
    'https://www.rtfox.top'
]

# ========================================
# 生产环境安全配置
# ========================================

if not DEBUG:
    # 强制 HTTPS 重定向（如果前端有 Nginx 处理可设为 False）
    SECURE_SSL_REDIRECT = True
    
    # Cookie 安全设置：仅通过 HTTPS 传输
    SESSION_COOKIE_SECURE = True  # 自动将 HTTP 请求重定向到 HTTPS
    CSRF_COOKIE_SECURE = True  # 确保 CSRF Cookie 仅通过 HTTPS 传输
    
    # HTTP 严格传输安全（HSTS）
    SECURE_HSTS_SECONDS = 31536000  # 1 年内只用 HTTPS 访问
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # HSTS 策略包括子域名
    SECURE_HSTS_PRELOAD = True  # 预加载
    
    # 防止浏览器猜测内容类型
    SECURE_CONTENT_TYPE_NOSNIFF = True  # 防止浏览器猜测内容类型
    
    # 启用浏览器 XSS 过滤器
    SECURE_BROWSER_XSS_FILTER = True  # 启用浏览器 XSS 过滤器 （防止 XSS-跨站脚本攻击）
    
    # 代理 SSL 头（如果使用 Nginx 反向代理）
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'mental_health',
    'staff_dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'school_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 静态文件的 URL 前缀
STATIC_URL = 'static/'
# 静态文件的目录（开发环境必备）
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# 收集静态文件的目标目录（生产环境必备）
STATIC_ROOT = BASE_DIR / 'staticfiles'


AUTH_USER_MODEL = 'accounts.User'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# ========================================
# Celery 配置
# ========================================

# Celery Broker URL（使用 Redis）
CELERY_BROKER_URL = 'redis://localhost:6379/0'

# Celery 结果存储后端
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# 任务序列化格式
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# 时区配置（与 Django 保持一致）
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = False

# 任务结果过期时间（秒）
CELERY_RESULT_EXPIRES = 3600  # 1小时

# 任务执行时间限制（秒）
CELERY_TASK_TIME_LIMIT = 300  # 5分钟
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4分钟软限制

# ========================================
# Django 缓存配置（使用 Redis）
# ========================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # 使用数据库 1（与 Celery 隔离）
        'TIMEOUT': 3600,  # 默认缓存 1 小时
    }
}
