# Generated by Django 6.0.1 on 2026-01-24 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='会话ID')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '数据集',
                'verbose_name_plural': '数据集',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50, verbose_name='分析类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('result_data', models.JSONField(verbose_name='分析结果数据')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='analysis_results/', verbose_name='Excel文件')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='mental_health.uploadeddataset')),
            ],
            options={
                'verbose_name': '分析结果',
                'verbose_name_plural': '分析结果',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolGateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, verbose_name='学号')),
                ('entry_time', models.DateTimeField(verbose_name='校门进出时间')),
                ('direction', models.CharField(max_length=10, verbose_name='进出方向')),
                ('location', models.CharField(max_length=100, verbose_name='位置')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_records', to='mental_health.uploadeddataset')),
            ],
            options={
                'verbose_name': '校门进出记录',
                'verbose_name_plural': '校门进出记录',
                'indexes': [models.Index(fields=['student_id', 'entry_time'], name='mental_heal_student_8b5826_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetworkAccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, verbose_name='学号')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='访问域名')),
                ('use_vpn', models.BooleanField(verbose_name='是否使用VPN')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_records', to='mental_health.uploadeddataset')),
            ],
            options={
                'verbose_name': '网络访问记录',
                'verbose_name_plural': '网络访问记录',
                'indexes': [models.Index(fields=['student_id', 'start_time'], name='mental_heal_student_77a573_idx')],
            },
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, verbose_name='学号')),
                ('month', models.CharField(max_length=10, verbose_name='年份-月份')),
                ('subject_grades', models.JSONField(verbose_name='各科成绩')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='mental_health.uploadeddataset')),
            ],
            options={
                'verbose_name': '成绩记录',
                'verbose_name_plural': '成绩记录',
                'indexes': [models.Index(fields=['student_id', 'month'], name='mental_heal_student_a54b07_idx')],
            },
        ),
        migrations.CreateModel(
            name='DormGateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, verbose_name='学号')),
                ('entry_time', models.DateTimeField(verbose_name='寝室进出时间')),
                ('direction', models.CharField(max_length=10, verbose_name='进出方向')),
                ('building', models.CharField(max_length=100, verbose_name='楼栋')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorm_records', to='mental_health.uploadeddataset')),
            ],
            options={
                'verbose_name': '寝室门禁记录',
                'verbose_name_plural': '寝室门禁记录',
                'indexes': [models.Index(fields=['student_id', 'entry_time'], name='mental_heal_student_563de5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CanteenConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, verbose_name='学号')),
                ('month', models.CharField(max_length=10, verbose_name='年份-月份')),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='食堂消费额度（本月）')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canteen_records', to='mental_health.uploadeddataset')),
            ],
            options={
                'verbose_name': '食堂消费记录',
                'verbose_name_plural': '食堂消费记录',
                'indexes': [models.Index(fields=['student_id', 'month'], name='mental_heal_student_791dd2_idx')],
            },
        ),
    ]
