# Generated by Django 6.0.1 on 2026-03-01 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_counselor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='token_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Token 数'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='Token 用量'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='新对话', max_length=200, verbose_name='会话标题'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='message_session_time_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='session_user_updated_idx'),
        ),
    ]
